---
- name: Eliminar el archivo de repositorio de Docker heredado
  file:
    path: "{{ yum_repo_dir }}/docker.repo"
    state: absent
  when:
    - ansible_distribution in ["CentOS","RedHat"]
    - not is_ostree

- name: Asegurar que las versiones anteriores de Docker no estén instaladas. | Debian
  apt:
    name: '{{ docker_remove_packages_apt }}'
    state: absent
  when:
    - ansible_os_family == 'Debian'
    - (docker_versioned_pkg[docker_version | string] is search('docker-ce'))

- name: Asegurar que las versiones anteriores de Docker no estén instaladas. | RedHat
  yum:
    name: '{{ docker_remove_packages_yum }}'
    state: absent
  when:
    - ansible_os_family == 'RedHat'
    - (docker_versioned_pkg[docker_version | string] is search('docker-ce'))
    - not is_ostree
