---
- name: extract_file | Desempaquetar archivo
  unarchive:
    src: "{{ download.dest }}"
    dest: "{{ download.dest | dirname }}"
    owner: "{{ download.owner | default(omit) }}"
    mode: "{{ download.mode | default(omit) }}"
    copy: no
  when:
    - download.unarchive | default(false)
