---
- name: download | Preparar directorios y variables de trabajo
  import_tasks: prep_download.yml
  when:
    - not skip_downloads|default(false)
  tags:
    - download
    - upload

- name: download | Obtenga el binario de kubeadm y la lista de imágenes requeridas
  include_tasks: prep_kubeadm_images.yml
  when:
    - not skip_downloads|default(false)
    - inventory_hostname in groups['kube-master']
  tags:
    - download
    - upload

- name: download | Descargar archivos/imagenes
  include_tasks: "{{ include_file }}"
  with_dict: "{{ downloads | combine(kubeadm_images) }}"
  vars:
    download: "{{ download_defaults | combine(item.value) }}"
    include_file: "download_{% if download.container %}container{% else %}file{% endif %}.yml"
  when:
    - not skip_downloads | default(false)
    - download.enabled
    - item.value.enabled
    - (not (item.value.container | default(false))) or (item.value.container and download_container)
    - (download_run_once and inventory_hostname == download_delegate) or (group_names | intersect(download.groups) | length)
