---
dependencies:
  - role: kubernetes-apps/ansible
    when:
      - inventory_hostname == groups['kube-master'][0]
    tags:
      - apps

  - role: kubernetes-apps/helm
    when:
      - helm_enabled
    tags:
      - apps
      - helm

  - role: kubernetes-apps/metallb
    when:
      - metallb_enabled
      - inventory_hostname == groups['kube-master'][0]
    tags:
      - metallb

  - role: kubernetes-apps/metrics_server
    when:
      - metrics_server_enabled
      - inventory_hostname == groups['kube-master'][0]
    tags:
      - apps
      - metrics_server    
