---
- hosts: localhost
  gather_facts: false
  become: no
  vars:
    minimal_ansible_version: 2.8.0
    ansible_connection: local
  tasks:
    - name: "Verificar versión Ansible >={{ minimal_ansible_version }}"
      assert:
        msg: "Ansible debe ser versión {{ minimal_ansible_version }} o mayor"
        that:
          - ansible_version.string is version(minimal_ansible_version, ">=")
      tags:
        - check
