---
- name: Verificar la versión de Ansible
  import_playbook: ansible_version.yml

- hosts: all
  gather_facts: false
  tags: always
  tasks:
    - name: "Configurar variable entorno de proxy"
      set_fact:
        proxy_env:
          http_proxy: "{{ http_proxy | default ('') }}"
          HTTP_PROXY: "{{ http_proxy | default ('') }}"
          https_proxy: "{{ https_proxy | default ('') }}"
          HTTPS_PROXY: "{{ https_proxy | default ('') }}"
          no_proxy: "{{ no_proxy | default ('') }}"
          NO_PROXY: "{{ no_proxy | default ('') }}"
      no_log: true

- hosts: bastion[0]
  gather_facts: False
  roles:
    - { role: ansiblerole-defaults}
    - { role: bastion-ssh-config, tags: ["localhost", "bastion"]}

- name: Reunir datos
  import_playbook: facts.yml

- hosts: nfs
  gather_facts: False
  vars_prompt:
    name: "confirmar"
    prompt: "Estas seguro de iniciar servidor NFS? Escriba 'si' para iniciar."
    default: "no"
    private: no

  pre_tasks:
    - name: comprobar la confirmación
      fail:
        msg: "Crear servidor NFS fue abortado"
      when: confirmar != "si"

  roles:
    - { role: ansiblerole-defaults}
    - role: init-k8s-nodo
      tags: init-k8s-nodo
      vars:
        init_k8s_nodo: true
    - role: init-nfs-nodo
      tags: init-nfs-nodo
      vars:
        init_nfs_nodo: true
        sub_net_destino: 172.28.12.0/24