---
#Carpeta temporal de manifiestos
networkpolicies_config_dir_temp: /tmp/networkpolicies
usuario_networkpolicies_group: root
networkpolicies_ingress_config_dir_temp: /tmp/networkpolicies/ingress
networkpolicies_egress_config_dir_temp: /tmp/networkpolicies/egress

networkpolicies:
  ingress:
    enabled: false
    deny_all_trafico: #Denegar todo el tráfico a una aplicación
      enabled: false
      namespace: "default"
      nombre: "nombrellabelpodx-deny-all"
      pod_matchlabels:
        app: web
    limit_all_trafico: #Limitar el tráfico a una aplicación
      enabled: false
      namespace: "default"
      nombre: "nombrellabelpodx-allow"
      pod_matchlabels:
        app: bookstore
        role: api
      from_pod_matchlabels:
        app: bookstore
    allow_all_trafico: #Permitir todo el tráfico a una aplicación
      enabled: false
      namespace: "default"
      nombre: "nombrellabelpodx-allow-all"
      pod_matchlabels:
        app: web
    deny_all_trafico_en_ns: #Denegar todo el tráfico entre pods de un mismo namespace y otros
      enabled: false
      namespace: "default"
    deny_all_trafico_otros_ns: #Denegar todo el tráfico de otros namespace
      enabled: false
      namespace: "default"
    allow_all_trafico_otros_ns_a_pod: #Permitir todo el tráfico desde todos los namespace hacia una aplicacion
      enabled: false
      namespace: "default"
      nombre: "default"
      pod_matchlabels:
        app: web
    allow_trafico_from_a_ns_a_pod: #Permitir todo el tráfico de ciertos namespaces hacia una aplicacion de un namespace
      enabled: false
      namespace: "default"
      nombre: "default"
      pod_matchlabels:
        app: web
      ns_matchlabels:
        labelns: produccion
    allow_trafico_algunos_ns_a_app: #Permitir el tráfico de algunos pods en otros namespaces hacia pods de un namespace
      enabled: false
      namespace: "default"
      nombre: "default"
      pod_matchlabels:
        app: web
      ns_matchlabels:
        labelns: produccion
      from_pod_matchlabels:
        app: monitoreo
    allow_trafico_solo_un_puerto_app: #Permitir el tráfico de una aplicacion mediante un puerto
      enabled: false
      namespace: "default"
      nombre: "app-allow-port"
      nro_puerto: 6000
      pod_matchlabels:
        app: web
      from_pod_matchlabels:
        app: prometheus
    allow_trafico_con_multiple_selectors_app: #Permitir el tráfico de una aplicacion mediante multiple selectores
      enabled: false
      namespace: "default"
      nombre: "app-allow-servicios"
      pod_matchlabels:
        app: bookstore
        role: db
      from_pod_matchlabels:
        - podSelector:
            matchLabels:
              app: bookstore
              role: search
        - podSelector:
            matchLabels:
              app: bookstore
              role: api
        - podSelector:
            matchLabels:
              app: inventory
              role: web
  egress:
    enabled: false
    deny_all_trafico_app: #Denegar tráfico de salida de una aplicación
      enabled: false
      namespace: "default"
      nombre: "nombrellabelpodx-deny-egress"
      pod_matchlabels:
        app: web
    deny_all_trafico_ns: #Denegar todo el tráfico no incluido en la lista blanca de un namespace
      enabled: false
      namespace: "default"
    deny_all_menos_dns_trafico_ns: #Denegar todo el tráfico menos DNS no incluido en la lista blanca de un namespace
      enabled: false
      namespace: "default"
    deny_all_trafico_external: #Denegar todo el tráfico de salida externo
      enabled: false
      namespace: "default"
      nombre: "nombrellabelpodx-external-egress"
      pod_matchlabels:
        app: web