---
- name: CNI | Asegurar que exista /opt/cni/bin
  file:
    path: /opt/cni/bin
    state: directory
    mode: 0755
    owner: kube
    recurse: true

- name: CNI | Copiar plugins cni 
  unarchive:
    src: "{{ local_release_dir }}/cni-plugins-linux-{{ image_arch }}-{{ cni_version }}.tgz"
    dest: "/opt/cni/bin"
    mode: 0755
    remote_src: yes
