apiVersion: v1
kind: Namespace
metadata:
  name: mysql-micro

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:privileged-k8s-admin
  namespace: mysql-micro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:privileged
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:authenticated

---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-micro-pv-claim-sc
  namespace: mysql-micro
spec:
  storageClassName: local-path-micro
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500M


---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-micro
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-micro
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        node-role.kubernetes.io/node-micro: ""
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/node-micro
                operator: In
                values:
                - ""     
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-micro-pv-claim-sc
