---
- name: Eliminar swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

# kubelet falla incluso si ansible_swaptotal_mb = 0
- name: Revisar swap
  command: /sbin/swapon -s
  register: swapon
  changed_when: no
- name: Inhabilitar swap
  command: /sbin/swapoff -a
  when: swapon.stdout
  ignore_errors: "{{ ansible_check_mode }}"
