---
- name: "Pre-upgrade | comprobar si existe el directorio de credenciales antiguo"
  stat:
    path: "{{ inventory_dir }}/../credentials"
  delegate_to: localhost
  connection: local
  register: old_credential_dir
  become: no

- name: "Pre-upgrade | comprobar si existe un nuevo directorio de credenciales"
  stat:
    path: "{{ inventory_dir }}/credentials"
  delegate_to: localhost
  connection: local
  register: new_credential_dir
  become: no
  when: old_credential_dir.stat.exists

- name: "Pre-upgrade | Mover datos del directorio credencial antiguo al nuevo"
  command: mv {{ inventory_dir }}/../credentials {{ inventory_dir }}/credentials
  args:
    creates: "{{ inventory_dir }}/credentials"
  delegate_to: localhost
  connection: local
  become: no
  when:
    - old_credential_dir.stat.exists
    - not new_credential_dir.stat.exists
