---
- name: Agregar domain/search/nameservers/options a resolv.conf
  blockinfile:
    path: "{{ resolvconffile }}"
    block: |-
      {% for item in [domainentry] + [searchentries] + nameserverentries.split(',') -%}
      {{ item }}
      {% endfor %}
      options ndots:{{ ndots }}
      options timeout:2
      options attempts:2
    state: present
    insertbefore: BOF
    create: yes
    backup: yes
    marker: "# Ansible entries {mark}"
  notify: Preinstall | propagar resolvconf a componentes k8s

- name: Eliminar las opciones search/domain/nameserver antes del block
  replace:
    dest: "{{ item[0] }}"
    regexp: '^{{ item[1] }}[^#]*(?=# Ansible entries BEGIN)'
    backup: yes
    follow: yes
  with_nested:
    - "{{ [resolvconffile, base|default(''), head|default('')] | difference(['']) }}"
    - [ 'search ', 'nameserver ', 'domain ', 'options ' ]
  notify: Preinstall | propagar resolvconf a componentes k8s

- name: Eliminar las opciones search/domain/nameserver despues block
  replace:
    dest: "{{ item[0] }}"
    regexp: '(# Ansible entries END\n(?:(?!^{{ item[1] }}).*\n)*)(?:^{{ item[1] }}.*\n?)+'
    replace: '\1'
    backup: yes
    follow: yes
  with_nested:
    - "{{ [resolvconffile, base|default(''), head|default('')] | difference(['']) }}"
    - [ 'search ', 'nameserver ', 'domain ', 'options ' ]
  notify: Preinstall | propagar resolvconf a componentes k8s