---
- name: NetworkManager | Agregar nameservers a configuracion NM
  ini_file:
    path: /etc/NetworkManager/conf.d/dns.conf
    section: global-dns-domain-*
    option: servers
    value: "{{ ( coredns_server + nameservers|d([]) + cloud_resolver|d([])) | unique | join(',') }}"
    mode: '0600'
    backup: yes
  notify: Preinstall | actualizar resolvconf para Fedora CoreOS

- name: NetworkManager | Agregar búsqueda de DNS a la configuración de NM
  ini_file:
    path: /etc/NetworkManager/conf.d/dns.conf
    section: global-dns
    option: searches
    value: "{{ ([ 'default.svc.' + dns_domain, 'svc.' + dns_domain ] + searchdomains|default([])) | join(',') }}"
    mode: '0600'
    backup: yes
  notify: Preinstall | actualizar resolvconf para Fedora CoreOS

- name: NetworkManager | Agregar opciones de DNS a la configuración de NM
  ini_file:
    path: /etc/NetworkManager/conf.d/dns.conf
    section: global-dns
    option: options
    value: "ndots:{{ ndots }};timeout:2;attempts:2;"
    mode: '0600'
    backup: yes
  notify: Preinstall | actualizar resolvconf para Fedora CoreOS
