---
- name: Configurar dhclient para reemplazar search/domain/nameservers
  blockinfile:
    block: |-
      {% for item in [ supersede_domain, supersede_search, supersede_nameserver ] -%}
      {{ item }}
      {% endfor %}
    path: "{{ dhclientconffile }}"
    create: yes
    state: present
    insertbefore: BOF
    backup: yes
    marker: "# Ansible entries {mark}"
  notify: Preinstall | propagate resolvconf to k8s components
  when: dhclientconffile is defined

- name: Configurar los hooks de dhclient para resolv.conf (non-RH)
  template:
    src: dhclient_dnsupdate.sh.j2
    dest: "{{ dhclienthookfile }}"
    owner: root
    mode: 0755
  notify: Preinstall | propagar resolvconf a componentes k8s
  when: ansible_os_family != "RedHat"

- name: Configurar los hooks de dhclient para resolv.conf (RH-only)
  template:
    src: dhclient_dnsupdate_rh.sh.j2
    dest: "{{ dhclienthookfile }}"
    owner: root
    mode: 0755
  notify: Preinstall | propagar resolvconf a componentes k8s
  when: ansible_os_family == "RedHat"
