---
# Deshabilitar swap
- import_tasks: 0010-swapoff.yml
  when:
    - not dns_late
    - disable_swap

- import_tasks: 0020-verify-settings.yml
  when:
    - not dns_late
  tags:
    - asserts

- import_tasks: 0030-pre_upgrade.yml
  run_once: true
  when:
    - not dns_late
  tags:
    - upgrade

- import_tasks: 0040-set_facts.yml
  tags:
    - resolvconf
    - facts

- import_tasks: 0050-create_directories.yml
  when:
    - not dns_late

- import_tasks: 0060-resolvconf.yml
  when:
    - dns_mode != 'none'
    - resolvconf_mode == 'host_resolvconf'
    - systemd_resolved_enabled.rc != 0
    - not is_fedora_coreos
  tags:
    - bootstrap-os
    - resolvconf

- import_tasks: 0061-systemd-resolved.yml
  when:
    - dns_mode != 'none'
    - resolvconf_mode == 'host_resolvconf'
    - systemd_resolved_enabled.rc == 0
  tags:
    - bootstrap-os
    - resolvconf

- import_tasks: 0062-networkmanager.yml
  when:
    - dns_mode != 'none'
    - resolvconf_mode == 'host_resolvconf'
    - is_fedora_coreos
  tags:
    - bootstrap-os
    - resolvconf

- import_tasks: 0070-system-packages.yml
  when:
    - not dns_late
  tags:
    - bootstrap-os

- import_tasks: 0080-system-configurations.yml
  when:
    - not dns_late
  tags:
    - bootstrap-os

- import_tasks: 0090-etchosts.yml
  when:
    - not dns_late
  tags:
    - bootstrap-os
    - etchosts

- import_tasks: 0100-dhclient-hooks.yml
  when:
    - dns_mode != 'none'
    - resolvconf_mode == 'host_resolvconf'
  tags:
    - bootstrap-os
    - resolvconf

- import_tasks: 0110-dhclient-hooks-undo.yml
  when:
    - dns_mode != 'none'
    - resolvconf_mode != 'host_resolvconf'
  tags:
    - bootstrap-os
    - resolvconf

# Necesitamos asegurarnos de que la red se reinicie lo suficientemente temprano para que la ventana acoplable pueda recuperar el sistema correcto más tarde
# nameservers y search domains
- meta: flush_handlers