---
- block:
  - name: Buscar controlador Docker cgroup
    shell: "docker info | grep 'Cgroup Driver' | awk -F': ' '{ print $2; }'"
    register: docker_cgroup_driver_result
    changed_when: false

  - name: Establecer el dato kubelet_cgroup_driver_detected para Docker
    set_fact:
      kubelet_cgroup_driver_detected: "{{ docker_cgroup_driver_result.stdout }}"
  when: container_manager == 'docker'

- name: Establecer variables especificas del SO
  include_vars: "{{ item }}"
  with_first_found:
  - files:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version|lower|replace('/', '_') }}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version|lower|replace('/', '_') }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"
    skip: true
