---
- name: Copia de seguridad de datos etcd
  command: /bin/true
  notify:
    - Actualizar datos tiempo
    - Establecer directorio de respaldo
    - Crear directorio de respaldo
    - Directorio de datos de estadísticas etcd v2
    - Copia de seguridad de datos etcd v2
    - Copia de seguridad de datos etcd v3
  when: etcd_cluster_is_healthy.rc == 0

- name: Actualizar datos tiempo
  setup: filter=ansible_date_time

- name: Establecer directorio de respaldo
  set_fact:
    etcd_backup_directory: "{{ etcd_backup_prefix }}/etcd-{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"

- name: Crear directorio de respaldo
  file:
    path: "{{ etcd_backup_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0600

- name: Directorio de datos de estadísticas etcd v2
  stat:
    path: "{{ etcd_data_dir }}/member"
  register: etcd_data_dir_member

- name: Copia de seguridad de datos etcd v2
  when: etcd_data_dir_member.stat.exists
  command: >-
    {{ bin_dir }}/etcdctl backup
      --data-dir {{ etcd_data_dir }}
      --backup-dir {{ etcd_backup_directory }}
  environment:
    ETCDCTL_API: 2
  retries: 3
  register: backup_v2_command
  until: backup_v2_command.rc == 0
  delay: "{{ retry_stagger | random + 3 }}"

- name: Copia de seguridad de datos etcd v3
  command: >-
    {{ bin_dir }}/etcdctl
      snapshot save {{ etcd_backup_directory }}/snapshot.db
  environment:
    ETCDCTL_API: 3
    ETCDCTL_ENDPOINTS: "{{ etcd_access_addresses.split(',') | first }}"
    ETCDCTL_CERT: "{{ etcd_cert_dir }}/admin-{{ inventory_hostname }}.pem"
    ETCDCTL_KEY: "{{ etcd_cert_dir }}/admin-{{ inventory_hostname }}-key.pem"
    ETCDCTL_CACERT: "{{ etcd_cert_dir }}/ca.pem"
  retries: 3
  register: etcd_backup_v3_command
  until: etcd_backup_v3_command.rc == 0
  delay: "{{ retry_stagger | random + 3 }}"
