---
- name: install | Copie el binario etcd y etcdctl del directorio de descargas
  copy:
    src: "{{ local_release_dir }}/etcd-{{ etcd_version }}-linux-{{ host_architecture }}/{{ item }}"
    dest: "{{ bin_dir }}/{{ item }}"
    mode: 0755
    remote_src: yes
  with_items:
  - etcd
  - etcdctl
  when: etcd_cluster_setup
