---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-crd-cr
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-crd-crb
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cloud-crd-cr
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-rolebindings-view-cr
rules:
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - rolebindings
      - roles
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-rolebindings-edit-cr
rules:
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrole-clusterrolebindings-view-cr
rules:
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterrolebindings
      - clusterroles
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrole-clusterrolebindings-edit-cr
rules:
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterrolebindings
      - clusterroles
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update



---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pv-view-cr
rules:
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - persistentvolume
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pv-edit-cr
rules:
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - persistentvolume
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-role-rolebindings-view-rb
  namespace: tools-cloud
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: role-rolebindings-view-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-role-rolebindings-edit-rb
  namespace: tools-cloud
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: role-rolebindings-edit-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-role-rolebindings-edit-rb
  namespace: cloud-ns
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: role-rolebindings-edit-cr
  apiGroup: rbac.authorization.k8s.io
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-clusterrole-clusterrolebindings-view-rb
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: clusterrole-clusterrolebindings-view-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-clusterrole-clusterrolebindings-edit-rb
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: clusterrole-clusterrolebindings-edit-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp-view-cr
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp-edit-cr
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - create
  - delete
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp-view-cr:cloud
roleRef:
  kind: ClusterRole
  name: psp-view-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: cloud

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp-edit-cr:cloud
roleRef:
  kind: ClusterRole
  name: psp-edit-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: cloud

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-mutwebhookconfgs-view-cr
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: 
    - "get"
    - "list"
    - "watch"
    - "patch"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-mutwebhookconfgs-edit-cr
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: 
    - create
    - delete
    - patch
    - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-mutwebhookconfgs-view-rb
  namespace: tools-cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-mutwebhookconfgs-view-cr
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-mutwebhookconfgs-view-crb
  namespace: tools-cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-mutwebhookconfgs-view-cr
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-mutwebhookconfgs-edit-crb
  namespace: tools-cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-mutwebhookconfgs-edit-cr
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-tokenreviews-view-cr
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: 
    - "get"
    - "list"
    - "watch"
    - "patch"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-tokenreviews-edit-cr
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: 
    - create
    - delete
    - patch
    - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-subjectaccessreviews-view-cr
rules:
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: 
    - "get"
    - "list"
    - "watch"
    - "patch"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-subjectaccessreviews-edit-cr
rules:
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: 
    - create
    - delete
    - patch
    - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-tokenreviews-view-crb
  namespace: tools-cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-tokenreviews-view-cr
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-tokenreviews-edit-crb
  namespace: tools-cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-tokenreviews-edit-cr
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-subjectaccessreviews-view-crb
  namespace: tools-cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-subjectaccessreviews-view-cr
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-subjectaccessreviews-edit-crb
  namespace: tools-cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloud-subjectaccessreviews-edit-cr
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-pv-view-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pv-view-cr
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-pv-edit-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pv-edit-cr
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io


---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-view-cr
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-edit-cr
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-pod-view-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-view-cr
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-traefik-ingress-controller-view-rb
  namespace: ingress-lan
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: traefik-ingress-controller-view-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-traefik-ingress-controller-view-rb
  namespace: devops-ns
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: traefik-ingress-controller-view-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-traefik-ingress-controller-view-rb
  namespace: monitoring
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: traefik-ingress-controller-view-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-traefik-ingress-controller-view-rb
  namespace: logging
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: traefik-ingress-controller-view-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-traefik-ingress-controller-view-rb
  namespace: cluster-tools
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: traefik-ingress-controller-view-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-traefik-ingress-controller-edit-rb
  namespace: ingress-lan
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: traefik-ingress-controller-edit-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-traefik-ingress-controller-edit-rb
  namespace: devops-ns
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: traefik-ingress-controller-edit-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-traefik-ingress-controller-edit-rb
  namespace: monitoring
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: traefik-ingress-controller-edit-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-traefik-ingress-controller-edit-rb
  namespace: logging
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: traefik-ingress-controller-edit-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-traefik-ingress-controller-edit-rb
  namespace: cluster-tools
subjects:
  - kind: Group
    name: cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: traefik-ingress-controller-edit-cr
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-traefik-internal-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller-view-cr
subjects:
  - kind: User
    name: cloud-admin

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-traefik-internal-edit-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller-edit-cr
subjects:
  - kind: User
    name: cloud-admin