---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: develop-crd-cr
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: develop-role-rolebindings-view-cr
rules:
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - rolebindings
      - roles
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: develop-role-rolebindings-edit-cr
rules:
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
---
#istio inicio

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: develop-gateway-vservice-view-cr
rules:
  - apiGroups:
      - "networking.istio.io"
    resources:
      - gateways
      - virtualServices
      - destinationrules
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: develop-gateway-vservice-edit-cr
rules:
  - apiGroups:
      - "networking.istio.io"
    resources:
      - gateways
      - virtualServices
      - destinationrules
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
---
#istio fin