---
- name: Kubeadm | restart kubelet
  command: /bin/true
  notify:
    - Kubeadm | reload systemd
    - Kubeadm | recargar kubelet

- name: Kubeadm | reload systemd
  systemd:
    daemon_reload: true

- name: Kubeadm | recargar kubelet
  service:
    name: kubelet
    state: restarted
