---
addusers:
  - name: etcd
    comment: "Usuario Etcd"
    createhome: yes
    home: "{{ etcd_data_dir }}"
    system: yes
    shell: /sbin/nologin

  - name: kube
    comment: "Usuario Kubernetes"
    createhome: no
    system: yes
    shell: /sbin/nologin
    group: "{{ kube_cert_group }}"
