---
- name: Kubernetes Apps | Listar plantillas de autorizacion
  set_fact:
    autorizar_templates:
      - {file: autorizar-ns.yml, type: ns, name: autorizar-namespace}
      - {file: autorizar-role.yml, type: role, name: autorizar}
      - {file: autorizar-rolebinding.yml, type: rolebinding, name: autorizar}
    autorizar_templates_for_psp:
      - {file: autorizar-psp.yml, type: podsecuritypolicy, name: autorizar-policy}
      - {file: autorizar-psp-clusterrole.yml, type: clusterrole, name: autorizar}
      - {file: autorizar-psp-clusterrolebinding.yml, type: clusterrolebinding, name: autorizar}

- name: Kubernetes Apps | Agregar plantillas adicionales a la lista de plantillas de autorizar para PodSecurityPolicy
  set_fact:
    autorizar_templates: "{{ autorizar_templates + autorizar_templates_for_psp }}"
  when: podsecuritypolicy_enabled

- name: "Kubernetes Apps | Crear directorio para manifiestos de usuario (en {{ groups['kube-master'][0] }})"
  file:
    path: "{{ autorizar_config_dir_temp }}"
    group: "{{ usuario_cert_group }}"
    state: directory
    owner: kube
    recurse: yes
    mode: 0700
  run_once: yes
  when: inventory_hostname == groups['kube-master'][0]
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: Kubernetes Apps | Copiar plantilla autorizar
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ autorizar_config_dir_temp }}/{{ item.file }}"
  with_items: "{{ autorizar_templates }}"
  register: manifests
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: Kubernetes Apps | Recursos de inicio autorizacion
  kube:
    name: "{{ item.item.name }}"
    namespace: "{{ autorizar_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    resource: "{{ item.item.type }}"
    filename: "{{ autorizar_config_dir_temp }}/{{ item.item.file }}"
    state: "latest"
  with_items: "{{ manifests.results }}"
  when: inventory_hostname == groups['kube-master'][0] and not item is skipped
