---
- name: Busqueda de IP de nodo en Kubernetes
  shell: >-
    {{ bin_dir }}/kubectl get nodes {{ node }}
    -o jsonpath='{range.status.addresses[?(@.type=="InternalIP")]}{.address}{"\n"}{end}'
  register: remover_nodo_ip
  when:
    - inventory_hostname in groups['etcd']
    - ip is not defined
    - access_ip is not defined
  delegate_to: "{{ groups['etcd']|first }}"
  failed_when: false

- name: Establecer IP de nodo
  set_fact:
    nodo_ip: "{{ ip | default(access_ip | default(remover_nodo_ip.stdout)) | trim }}"
  when:
    - inventory_hostname in groups['etcd']

- name: Verificar que nodo_ip sea definido y con valor
  assert:
    that: nodo_ip is defined and nodo_ip | length > 0
    msg: "El IP del nodo Etcd no esta definido y sin valor"
  when:
    - inventory_hostname in groups['etcd']

- name: Buscar id de miembro etcd
  shell: "{{ bin_dir }}/etcdctl member list | grep {{ nodo_ip }} | cut -d, -f1"
  register: etcd_miembro_id
  ignore_errors: true
  changed_when: false
  check_mode: no
  tags:
    - facts
  environment:
    ETCDCTL_API: 3
    ETCDCTL_CERT: "{{ etcd_cert_dir }}/admin-{{ inventory_hostname }}.pem"
    ETCDCTL_KEY: "{{ etcd_cert_dir }}/admin-{{ inventory_hostname }}-key.pem"
    ETCDCTL_CACERT: "{{ etcd_cert_dir }}/ca.pem"
    ETCDCTL_ENDPOINTS: "{{ etcd_access_addresses }}"
  delegate_to: "{{ groups['etcd']|first }}"
  when: inventory_hostname in groups['etcd']

- name: Remover nodo miembro de cluster etcd
  command: "{{ bin_dir }}/etcdctl member remove {{ etcd_miembro_id.stdout }}"
  register: etcd_member_in_cluster
  changed_when: false
  check_mode: no
  tags:
    - facts
  environment:
    ETCDCTL_API: 3
    ETCDCTL_CERT: "{{ etcd_cert_dir }}/admin-{{ inventory_hostname }}.pem"
    ETCDCTL_KEY: "{{ etcd_cert_dir }}/admin-{{ inventory_hostname }}-key.pem"
    ETCDCTL_CACERT: "{{ etcd_cert_dir }}/ca.pem"
    ETCDCTL_ENDPOINTS: "{{ etcd_access_addresses }}"
  delegate_to: "{{ groups['etcd']|first }}"
  when:
    - inventory_hostname in groups['etcd']
    - etcd_miembro_id.stdout | length > 0
